version: "3.3"

services:
  web-ide-frontend:
    container_name: web-ide-frontend
    build: ./config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /code:/config/current-repository
    ports:
      - "8443:8443"
    restart: unless-stopped
