version: "3.3"

services:
  frontend:
    container_name: web-ide-frontend
    build: ./frontend/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /code:/config/current-repository
    ports:
      - "8443:8443"
    restart: unless-stopped
    
  backend:
    build: ./backend/src
    network_mode: "host"
    container_name: web-ide-backend
    volumes:
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - /var/run/dbus:/var/run/dbus
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    build: ./nginx
    network_mode: "host"
    container_name: web-ide-nginx